name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run snmpsim
      run: docker-compose -f environment/compose/docker-compose.yaml up -d
    - name: Run bench
      run: |
        python run_bench.py localhost 1161 --oid-batch-size 50 --sessions 1 --rounds 10
